title: NBSafety
subtitle: "Fearless interactivity for Jupyter notebooks."
description: "NBSafety makes it easier to reason about out-of-order execution in Jupyter notebooks."
author: NBSafety
language: en
timezone: UTC

url: https://nbsafety.org
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0
pretty_urls:
  trailing_index: false
  trailing_html: false

theme: navy

highlight:
  enable: true
  line_number: false

github: nbsafety-project/nbsafety
