<!-- GitHub star -->
<a href="https://github.com/nbsafety-project/nbsafety" target="_blank" aria-label="Star nbsafety-project/nbsafety on GitHub"><img src="https://img.shields.io/github/stars/nbsafety-project/nbsafety?style=social" alt="Star"></a>
<!-- GitHub fork -->
<a href="https://github.com/nbsafety-project/nbsafety" target="_blank" aria-label="Fork nbsafety-project/nbsafety on GitHub"><img src="https://img.shields.io/github/forks/nbsafety-project/nbsafety?style=social" alt="Fork"></a>
<!-- PyPI Download -->
<a href="https://pypi.org/project/nbsafety/" target="_blank" aria-label="NBsafety on PyPI"><img src ="http://img.shields.io/pypi/dm/nbsafety?logo=pypi&style=social" alt="PyPI Downloads"></a>
